const APP_ENVS = {
  EXPO_PUBLIC_API_URL: process.env.EXPO_PUBLIC_API_URL + "/api/v1",
  EXPO_PUBLIC_GOOGLE_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_CLIENT_ID,
  EXPO_PUBLIC_SECRET_KEY: process.env.EXPO_PUBLIC_SECRET_KEY,
};

export default APP_ENVS;
